// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLayer.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EntityLayer.Ayarlar", b =>
                {
                    b.Property<int>("AyarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AyarId"), 1L, 1);

                    b.Property<bool>("BugunOncesi")
                        .HasColumnType("bit");

                    b.Property<int>("KacHaftaOnce")
                        .HasColumnType("int");

                    b.HasKey("AyarId");

                    b.ToTable("tbl_ayarlar");
                });

            modelBuilder.Entity("EntityLayer.GiderTablosu", b =>
                {
                    b.Property<int>("GiderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GiderId"), 1L, 1);

                    b.Property<string>("GiderAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GiderTipId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("GiderId");

                    b.HasIndex("GiderTipId");

                    b.ToTable("tbl_Giderler");
                });

            modelBuilder.Entity("EntityLayer.GiderTip", b =>
                {
                    b.Property<int>("GiderTipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GiderTipId"), 1L, 1);

                    b.Property<string>("GiderTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RenkKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GiderTipId");

                    b.ToTable("tbl_GiderTipleri");
                });

            modelBuilder.Entity("EntityLayer.GiderTablosu", b =>
                {
                    b.HasOne("EntityLayer.GiderTip", "GiderTip")
                        .WithMany("Giderler")
                        .HasForeignKey("GiderTipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiderTip");
                });

            modelBuilder.Entity("EntityLayer.GiderTip", b =>
                {
                    b.Navigation("Giderler");
                });
#pragma warning restore 612, 618
        }
    }
}
